"""empty message

Revision ID: 10908715395d
Revises: 565ffd5984d2
Create Date: 2026-06-19 19:25:56.356860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10908715395d'
down_revision = '565ffd5984d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('foro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['foro_id'], ['foro.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow')
    # ### end Alembic commands ###
