"""empty message

Revision ID: 213c18e55927
Revises: 9e450bf54d06
Create Date: 2026-06-12 19:22:12.296884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213c18e55927'
down_revision = '9e450bf54d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_select',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('foro_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['foro_id'], ['foro.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tag_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tag_foro_id_fkey'), type_='foreignkey')
        batch_op.drop_column('foro_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('foro_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('tag_foro_id_fkey'), 'foro', ['foro_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('tag_user_id_fkey'), 'user', ['user_id'], ['id'])

    op.drop_table('tag_select')
    # ### end Alembic commands ###
