"""empty message

Revision ID: 971fc0e32642
Revises: 23b60353e5e5
Create Date: 2026-06-10 21:01:04.464449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971fc0e32642'
down_revision = '23b60353e5e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foro', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('foro_title_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foro', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('foro_title_key'), ['title'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
